name: Deploy PR previews

env:
  PR_NUMBER: ${{ github.event.number }}


on:
  pull_request:
    branches: [ "main" ]

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: replace base url
        run: |
          sed -i "s|routeBasePath:.*|routeBasePath: '/pr-preview/pr-$PR_NUMBER/',|g" docusaurus.config.js

      - name: Build website
        run: yarn build

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./build
