name: Deploy PR previews

env:
  PR_NUMBER: ${{ github.event.number }}


on:
  pull_request:
    branches: [ "main" ]

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: replace base url
        run: |
          # Rewrite base path to support dynamic pr uri
          sed -i "s|routeBasePath:.*|routeBasePath: '/pr-preview/pr-$PR_NUMBER/',|g" docusaurus.config.js
          # remove redirects for preview is breaking build.
          # TODO This is Janky hopefully we can retire redirects soon hardcoding line numbers is fragile
          sed -i '54,216d;' docusaurus.config.js
          # warn on broken links for preview for now not ideal just testing this out for now
          sed -i "s|onBrokenLinks:.*|onBrokenLinks: 'log',|g" docusaurus.config.js
          sed -i "s|onBrokenMarkdownLinks:.*|onBrokenMarkdownLinks: 'log',|g" docusaurus.config.js
          cat docusaurus.config.js


      - name: Build website
        run: yarn build

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./build
